spring:
  data:
    mongodb:
      uri: mongodb://localhost/tg
      auto-index-creation: true


kuku:
  telegram:
    token:
    username: kuku
    creatorId: -1
    proxyHost:
    proxyPort: 0
    proxyType: NO_PROXY
    url: