spring:
  data:
    mongodb:
      uri: mongodb://localhost/tg
      auto-index-creation: true
  task:
    scheduling:
      pool:
        size: 10


kuku:
  telegram:
    token:
    username: kuku
    creatorId: -1
    proxyHost:
    proxyPort: 0
    proxyType: NO_PROXY
    url:
